spring:
  datasource:
    url: jdbc:mysql://localhost:3306/root?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root1234
    drivcerClassName : com.mysql.jdbc.Driver
    max-active : 20
    max-idle: 8
    min-idle: 8
    initial-size: 10
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy:  org.hibernate.cfg.ImprovedNamingStrategy
    properties:
     hibernate:
       dialect: org.hibernate.dialect.MySQL5Dialect

  application:
    name: springboot
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms:  true
    virtual-host:  /

  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    cache: false
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html





